### ISSUE TITLE
Feature: Support flag to crawl only the root website. Do not hop to external links

### ISSUE THREAD

**Issue by indrajithi** [indrajithi/tiny-web-crawler#11]
- Very straightforward feature to add a flag to crawl only the root website and do not crawl to external links. 
- eg: If the root url provided is https://github.com. It should crawl pages in this domain only. It should not crawl https://exmaple.com 

- (optional) Can we also support an option to crawl only external links and no internal links. There could be some use cases for that

**Comment by Mews** [comment]
I have a question, isn't this achievable through `max_links=0` in the `Spider` class?

**Comment by indrajithi** [comment]
if we set max_link=0 it will crawl only the `root_url` once. 

Say for example we are passing the root_url as `https://github.com`. It will crawl only this page and fetch all the links in this page. It will not crawl `https://github.com/indrajithi/tiny-web-crawler` and fetch links in that. `max_links` is the number of urls/links crawled. 

What we want to achieve in this issue is we that, it should only crawl internal links. 

Every links that has `https://github.com/` in it. And do not crawl external links. 

This will be useful in creating sitemap for a website. LMK if you have any more questions. 
@Mews

**Comment by Mews** [comment]
Alright makes sense. What should I call the argument then, something like `crawl_external_links`? And the default would be true?

**Comment by Mews** [comment]
Oh wait there's already a pr open for this

**Comment by indrajithi** [comment]
> Oh wait there's already a pr open for this

Would you like to pick [this](https://github.com/indrajithi/tiny-web-crawler/issues/13) up? This is very similar to what we discussed.

**Comment by Mews** [comment]
Sure!

**Comment by indrajithi** [comment]
@devavinothm Are you working on this? https://github.com/indrajithi/tiny-web-crawler/pull/14

**Comment by Mews** [comment]
@indrajithi I can complete his pr if you want

**Comment by indrajithi** [comment]
@Mews I have updated the description. Assigning to you. 🥇

**Comment by Mews** [comment]
Thanks, I'm going to sleep right now but I'll get to it tomorrow morning :)
