### ISSUE TITLE
Feature: Support for regular expression pattern for url crawling 

### ISSUE THREAD

**Issue by indrajithi** [indrajithi/tiny-web-crawler#13]
- Only crawl the websites which matches the regular expression pattern

**Comment by indrajithi** [comment]
@Mews Let me know if I can assign this to you. Thanks!

**Comment by Mews** [comment]
Yep, go ahead.

**Comment by Mews** [comment]
Are there any pre-commit hooks I should install?

**Comment by indrajithi** [comment]
Yes, I have added a pre commit hook to check for lint errors. `poetry install --with dev` should trigger script.py and install the pre-commit hook. LMK if it does not work. If not you can manually install the hook

**Comment by indrajithi** [comment]
Done in this [#PR](https://github.com/indrajithi/tiny-web-crawler/pull/16). Closing
