### ISSUE TITLE
Make `Spider` importable from main module

### ISSUE THREAD

**Issue by Mews** [indrajithi/tiny-web-crawler#26]
Feels like you should be able to do `from tiny_web_crawler import Spider`, not just `from tiny_web_crawler.crawler import Spider`

Would be as simple as adding `from tiny_web_crawler.crawler import Spider` to `__init__.py`

Edit:

- Update how we import the package and update the readme usage doc (moved from #9 )

**Comment by indrajithi** [comment]
Adding this to #17

**Comment by indrajithi** [comment]
I think we should prioritise this because after #9, our usage doc is outdated. We can also consider releasing a beta version `v.0.4.0-beta.1` and make sure the current changes are working.
